### ISSUE TITLE
[KubeRay-ApiServer] Not able to create/update cluster autoscaling via apiserver

### ISSUE THREAD

**Issue by anovv** [ray-project/kuberay#1024]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

apiserver

### What happened + What you expected to happen

Asked [question](https://discuss.ray.io/t/kuberay-enabling-configuring-autoscaling-via-kuberay-apiserver-and-or-ray-cluster-helm-chart/8112) and was redirected here

Went through [the guide](https://ray-project.github.io/kuberay/components/apiserver/) and found no info on how to set up autoscaling cluster with apiserver. If it is possible, docs should be updated?

Also noticed that the cluster config spec is inconsistent between three management options (RayCluster crd, kuberay-apiserver requests payloads, ray-cluster helm chart). Is it intentional? Is it possible to enable autoscaling via apiserver/helm chart?

### Reproduction script

-

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
Hi @dirtyValera,

Thank you for reporting this issue! Would you mind sharing why do you want to use KubeRay APIServer?

> Also noticed that the cluster config spec is inconsistent between three management options (RayCluster crd, kuberay-apiserver requests payloads, ray-cluster helm chart). Is it intentional?

Yes, I would recommend using Helm charts or YAML files to deploy a RayCluster, instead of using the KubeRay APIServer. We do not have any integration tests for KubeRay APIServer, and the component is community-managed and is not officially endorsed by the Ray maintainers.

This [document](https://ray-project.github.io/kuberay/guidance/autoscaler/) provides detailed instructions to deploy a RayCluster with autoscaler.

**Comment by kevin85421** [comment]
This issue has been inactive for 9 months. Close the issue.
