### ISSUE TITLE
[Refactor] Rename rayiov1alpha1 and rayv1alpha1 to v1alpha1

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#1079]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### 1. "kuberay/ray-operator/apis/ray/v1alpha1" 

In the KubeRay codebase, there are three aliases for v1alpha1: rayiov1alpha1, rayv1alpha1, and v1alpha1. Let's ensure consistency across all of them.

* Case 1: https://github.com/ray-project/kuberay/blob/b0649c43bbae3a0ac4917f94d80cbde466bb4f88/ray-operator/controllers/ray/utils/util.go#L21

* Case 2: https://github.com/ray-project/kuberay/blob/b0649c43bbae3a0ac4917f94d80cbde466bb4f88/ray-operator/controllers/ray/utils/dashboard_httpclient.go#L21

* Case 3: https://github.com/ray-project/kuberay/blob/b0649c43bbae3a0ac4917f94d80cbde466bb4f88/ray-operator/controllers/ray/common/rbac.go#L4

<del>Use Case 3 to replace Case 1 and Case 2.</del>

[Update]: Use Case 2 to replace Case 1 and Case 3.

### Reproduction script

No

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by gvspraveen** [comment]
One of the difficult here is also because we have multiple go packages named v1alpha1

Example:

`github.com/ray-project/kuberay/ray-operator/apis/ray/v1alpha1`
`github.com/ray-project/kuberay/ray-operator/pkg/client/listers/ray/v1alpha1`

So when importing both in same go file, we have to distinguish between them. Example:
https://github.com/ray-project/kuberay/blob/b0649c43bbae3a0ac4917f94d80cbde466bb4f88/ray-operator/pkg/client/informers/externalversions/ray/v1alpha1/rayservice.go#L9


So one option is when referring to `ray-operator/apis/ray/v1alpha1` call it `v1alpha1Operator` and when referring to `pkg/client/listers/ray/v1alpha1` call it `v1alpha1Client`.

**Comment by kevin85421** [comment]
@gvspraveen Good catch. I will update the issue description.

**Comment by kevin85421** [comment]
@gvspraveen I found that `github.com/ray-project/kuberay/ray-operator/pkg/client/listers/ray/v1alpha1` only happens in the generated client code. It does not be imported into the operator codebase.

* Generated code:
  https://github.com/ray-project/kuberay/blob/b0649c43bbae3a0ac4917f94d80cbde466bb4f88/ray-operator/pkg/client/informers/externalversions/ray/v1alpha1/raycluster.go#L12

**Comment by anishasthana** [comment]
Just wanted to check in -- is someone already working on this issue?

**Comment by kevin85421** [comment]
Hi @anishasthana, thank you for reaching out! Currently, there is no one assigned to this issue. If you are interested, I can assign this issue to you.

**Comment by anishasthana** [comment]
I'd be happy to pick this one up! I've been looking for good issues to get started with anyways :-)

**Comment by kevin85421** [comment]
Great! You can also take a look at https://github.com/ray-project/kuberay/issues/1059 and join our Slack channel to stay connected with the community.
