### ISSUE TITLE
[RayJob] Support `kubectl logs rayjobs/my-job` CLI

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/kuberay#1201]
Kubernetes jobs support viewing logs in two ways (https://kubernetes.io/docs/concepts/workloads/controllers/job/):

The first way is cumbersome:
```bash
pods=$(kubectl get pods --selector=batch.kubernetes.io/job-name=pi --output=jsonpath='{.items[*].metadata.name}')
kubectl logs $pods
```

The second way is easier:
```bash
kubectl logs jobs/pi
```

We should investigate whether it's possible to support the second way for RayJob:

```bash
kubectl logs rayjobs/pi
```

If it's possible, we should add it.

**Comment by rudeigerc** [comment]
Hi, unfortunately, as far as I'm concerned, it is not supported for CRDs since this part of logic was hardcoded into `kubectl`. A common way to achieve this is to implement subcommands in the project's CLI (e.g. [Tekton](https://tekton.dev/docs/pipelines/logs/) / [ArgoCD](https://argo-cd.readthedocs.io/en/stable/user-guide/commands/argocd_app_logs/)).

In the case of KubeRay, the CLI is actually communicated with KubeRay API Server. As a result, we have to implement this on both side (i.e. CLI and KubeRay API Server) to achieve the goal.

**Comment by architkulkarni** [comment]
Thanks for the details!

**Comment by kevin85421** [comment]
We decided to implement it in Ray CLI. Close this issue.
