### ISSUE TITLE
[Feature] Allow wait-gcs-ready to choose or bypass volumes to mount

### ISSUE THREAD

**Issue by richardsliu** [ray-project/kuberay#1280]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Currently Kuberay worker pods have an init-container for connecting to the Ray head. It attempts to mount all the volumes that the Ray container mounts: https://github.com/ray-project/kuberay/blob/master/ray-operator/controllers/ray/common/pod.go#L236

It would be helpful to add a way to select which volumes to mount, or bypass mounting completely. 

The reason is that some volumes may be backed by other volume types that require special drivers to be installed. For example, https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/issues/38.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
You can refer to [this document](https://github.com/ray-project/kuberay/blob/master/docs/guidance/FAQ.md#worker-init-container) to disable the init container injection and define your own init container.

**Comment by richardsliu** [comment]
Thanks is there an example of a custom init container?

**Comment by kevin85421** [comment]
You can refer to pod.go#L200 in #973. I will add a section in FAQ.md for more details later.

**Comment by richardsliu** [comment]
Also is this approach generally recommended? The comment in the helm chart template warns explicitly against it: https://github.com/ray-project/kuberay/blob/master/helm-chart/kuberay-operator/values.yaml#L85

For the long term, I suspect having user-injected custom init containers may not be sustainable since the code might diverge. 

Would it be possible to perhaps extract the actual code injected for the init container to a config map? Then if the user wishes to inject their own logic (like bypassing volumes), they can at least reuse the same container code.

**Comment by richardsliu** [comment]
Additionally, how about adding some template logic here to allow users to inject their init containers through Helm charts?

**Comment by kevin85421** [comment]
> Also is this approach generally recommended? The comment in the helm chart template warns explicitly against it: https://github.com/ray-project/kuberay/blob/master/helm-chart/kuberay-operator/values.yaml#L85

The job of the init container is quite straightforward: it merely waits for the GCS on the Ray head Pod to be ready. We've added the comment `Warning: we highly recommend setting this to true and allowing KubeRay to handle it for you.` This is because KubeRay users include not only infrastructure engineers who are familiar with Kubernetes, but also AI practitioners from small startups who focus on ML and may not have experience with Kubernetes.

We include these comments to encourage AI practitioners to use the default configurations and prevent potential misconfigurations. For infrastructure engineers, it's safe to define the init container independently.
