### ISSUE TITLE
[Feature] Add new worker groups to Ray Service without rollout

### ISSUE THREAD

**Issue by zcin** [ray-project/kuberay#1643]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

It would be useful to be able to add a new [worker group definition](https://docs.ray.io/en/latest/cluster/kubernetes/user-guides/config.html#pod-configuration-headgroupspec-and-workergroupspecs) to the Ray Cluster configuration without causing a new cluster rollout.

### Use case

I want to run Ray Serve applications in separate docker images. I can leverage worker groups nicely to do that.

The problem comes when I want to add a new Ray Serve application. In Serve, adding a new application is lightweight; a new application is started without touching any existing applications. But if I want to add a new application and define a new worker group for that app to run in, that will cause a new cluster rollout.

I want to be able to add new applications and define new worker groups without this happening.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by architkulkarni** [comment]
@kevin85421 Here's my rough plan:

1. The following functions should be refactored in some way to detect the case "workerGroup(s) added": https://github.com/ray-project/kuberay/blob/666679f8dfc5b7085fc0d93bea89aaa4d9a02c8b/ray-operator/controllers/ray/rayservice_controller.go#L1134-L1158 

2. In the RayService reconcile loop, currently we have two options, (1) create a new RayCluster or (2) do nothing to the RayCluster.  If the situation "new workerGroup(s) added" is detected, we will now add option (3), which is update the RayCluster via `r.Update()`

Does this sound good to you?

Another question: Should we handle the case where workerGroups are **removed**, or should we keep the old behavior which is to rollout a new Cluster in this case?

**Comment by kevin85421** [comment]
> In the RayService reconcile loop, currently we have two options, (1) create a new RayCluster or (2) do nothing to the RayCluster. If the situation "new workerGroup(s) added" is detected, we will now add option (3), which is update the RayCluster via r.Update()

This makes sense to me.

> Another question: Should we handle the case where workerGroups are removed, or should we keep the old behavior which is to rollout a new Cluster in this case?

Perhaps we could update the RayCluster (option 3) when the number of worker groups changes. Many users do not favor rolling out a new RayCluster, whether it is intended or unexpected.

**Comment by architkulkarni** [comment]
@kevin85421 Thanks, that's helpful! I just want to nail down the desired behavior:

If we update the cluster when adding or deleting worker groups, then doesn't this imply that we should also update the cluster even if only `Replicas` or `WorkersToDelete` changes? Because that's equivalent to deleting a worker group and adding back the same worker group but with the new `Replicas` or `WorkersToDelete`.  This would be a change from the existing behavior (which is to do nothing in this case.)

That means we'll have three options:

Option 1: Create a new RayCluster: If there are any changes outside of workerGroupSpecs
Option 2: Do Nothing: Only if the entire spec is identical (in particular, this includes `Replicas` and `WorkersToDelete`)
Option 3: Update the RayCluster: If the only changes are inside workerGroupSpec

So there will be no special handling of `Replicas` or `WorkersToDelete`.  

We could potentially eliminate Option 2 to simplify things, but my guess is that will cause too much overhead by calling `client.Update()` every reconciliation loop.

**Comment by kevin85421** [comment]
I think we should still retain option 2 (i.e. do nothing) for `Replicas` and `WorkersToDelete` in the short term. This may be a bit more complex than our imagination. Ray Autoscaler only updates RayCluster CR, so there is an inconsistency in the RayClusterSpec between the RayCluster CR and the RayService CR. Most RayService users use Ray Autoscaler because the nondeterministic property of model serving. It is better to make only one source of truth to manage these two fields (RayService controller or Ray Autoscaler). We can do it later if it is necessary.
