### ISSUE TITLE
[Feature] Adding RAY_CLOUD_INSTANCE_ID as unique id for Ray node 

### ISSUE THREAD

**Issue by rickyyx** [ray-project/kuberay#1751]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

To make Kuberay works with ray's Autoscaler v2, we need a unique ID that's unique during the lifetime of a ray cluster. 

This ID will be used by Ray's autoscaler to identify cloud instance (in this case, a kuberay pod). 

Defintion of the ID:
- We will use the pod name as the id. 
- In the alpha-release, we will ask users to set `restartPolicy=Never` to avoid kuberay restarting ray w/o Ray's knowledge. 

Passing of the ID:
The ID needs to be surfaced to both the ray processes, as well as the Kuberay node provider that is embedded in the ray autoscaler process. 
- Ray Process: Setting the env var `RAY_CLOUD_INSTANCE_ID` when starting ray will have the ray node picked up this for both head node and worker node.

### Use case

Ray Autoscaler V2

### Related issues

NA

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
I take a look at this issue today. The following is my current progress. We can discuss it offline next week.

* There is no simple way to pass the container’s restartCount as an environment variable.
* I consider using `$POD_NAME` and Ray cluster’s session (i.e. `session_2023-xx-xx_xx-xx-xx_xxxxx_xx` under `/tmp/ray`). However, it doesn’t work for Ray workers because when a worker restarts. The session will still be the same.
* [Sol 1]: A possible solution is to use the container ID. If we decide to go in this direction, I will need to investigate whether all container runtimes support this feature. Currently, I only know Docker supports this.
  ```sh
  > cat /proc/self/cgroup | grep "docker" | sed 's/^.*\///' | head -n 1
  cri-containerd-d739a180ae49cc523d38bb91d7fe34dfce32fadcc527fa6da27327a899765a49.scope
  ```
* [Sol 2]: Another solution is for Ray to maintain a file with the restart count or a unique random string. KubeRay could then ensure that `/tmp/ray` is always mounted in all Ray containers to prevent loss of data after a container restarts.

**Comment by rickyyx** [comment]
- Updated the issue requirement to only needing setting of `RAY_CLOUD_INSTANCE_ID=<pod-name>` for the alpha release.

**Comment by kevin85421** [comment]
Add more context explaining why we chose `POD_NAME` as the value for `RAY_CLOUD_INSTANCE_ID`. One of the most important scenarios that the Ray Autoscaler should avoid is deleting a Ray Pod that has a running Ray task or actor. 

* Example:
  * Ray Autoscaler drains a Ray Pod and tells the information to GCS.
  * KubeRay NodeProvider sends a patch request to update RayCluster CR (`replicas` and `WorkersToDelete`)
  * Something unexpected happens, and the Ray Pod restarts.
  * The new Ray node (the same Ray Pod) registers with the GCS.
  * Ray schedules some Ray tasks/actors to the new Ray node.
  * KubeRay reconciles and deletes the Pod because it is specified in `WorkersToDelete`.

If we can determine which Ray node belongs to which Ray Pod using `RAY_CLOUD_INSTANCE_ID`, the GCS can reject the registration of a new Ray node in the same Ray Pod that has already been drained. Hence, no task/actor will be scheduled on the new Ray node.
