### ISSUE TITLE
[Feature] Support ImagePullPolicy in Worker and Head NodeSpec  

### ISSUE THREAD

**Issue by revit13** [ray-project/kuberay#2047]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

At present, it's not possible to configure the image pull policy for both the head and worker nodes. By default, the `IfNotPresent` policy is applied.

**Comment by kevin85421** [comment]
cc @tedhtchang @z103cb @blublinsky

**Comment by blublinsky** [comment]
@kevin85421 once we complete current PR, we can look at other enhancements

**Comment by ravishtiwari** [comment]
Do we want to be able to specify the Image and Pull Policy at the head spec level here? Asking, since it is possible to specify pod template for   Ray CR:
```# Pod template
    template:
      spec:
        containers:
        # The Ray head container
        - name: ray-head
          image: rayproject/ray:2.9.0
 ``` 
 
 so, we can specify the image pull policy, per container level.
 
 However, if we want to be able to specify it here:
 ```
 headGroupSpec:
 ```
 or 
 ```
 workerGroupSpecs:
 ```
 then, yes, we need these changes

**Comment by blublinsky** [comment]
Its a useful and simple change. Can we, please, merge https://github.com/ray-project/kuberay/pull/1728 and then its an easy implementation
