### ISSUE TITLE
[Bug] The new SA used by autoscaler caused permission errors

### ISSUE THREAD

**Issue by daikeshi** [ray-project/kuberay#242]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

When I set `enableInTreeAutoscaling` to `true` for my Ray cluster, the kuberay-operator creates a new k8s service account with the same name of the cluster (if it's not available) and uses it for the head node pod (see [here](https://github.com/ray-project/kuberay/blob/master/ray-operator/controllers/raycluster_controller.go#L585)). Our Ray clusters on Kubernetes use a specific pre-configured service account in the namespace. Switching to a different service account would cause the permission issues when users try to use Ray to read the data. The autoscaler should use the existing service account defined in the `RayCluster` resource object for the head node instead of creating a new one to use.   

### Reproduction script

The bug can be reproduced by following these steps.
- Define a k8s service account named `default-sa`
- Create a RayCluster with the name of `foo` and use `default-sa` for its head node
- Set `enableInTreeAutoscaling` to true for the Ray cluster you just created
- The Kuberay operator will restart the head node pod, inject the autoscaler container, and use `foo` as its service account   

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

**Comment by Jeffwan** [comment]
@daikeshi I think this is a problem happen in your environment? BTW, The reason you have pre-configure service account is because it binds to GCP Service Account that has the permission to read the data? 

Let me try to understand the problem deeply. The ray program which reads the data is scheduled either on head or worker. Autoscaler container is embedded inside head pod and it creates worker without specifying the service account. It should use default one by default. 

ideally we should ask both head and worker use your preconfigured SA, right? So the problem is autoscaler create the pods without delegate sa to worker template? 

Is it ok to reuse the service account if RayCluster service account is provided?

**Comment by daikeshi** [comment]
Yes, we should reuse the service account if RayCluster service account is provided. 

In our case, the service account is pre-configured in each namespace with [GKE workload identity](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity). We currently deploy RayCluster directly via raw YAML manifests, so we are able to configure service account for the head node and workers. I think the workers launched by the autoscaler was able to pick up the correct service account defined in the RayCluster. It's just the head node that tries to use a new one when it's injecting the autoscaler container. We could simply check and reuse the existing one if RayCluster has the service account defined. 

We are happy to take a stab of this bug.
