### ISSUE TITLE
[Docs] The links for example Rayclusters are broken 

### ISSUE THREAD

**Issue by goswamig** [ray-project/kuberay#291]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Examples `RayClusters` in [this](https://ray-project.github.io/kuberay/components/operator/#running-an-example-cluster) link is broken. 

[ray-cluster.mini.yaml](https://ray-project.github.io/kuberay/components/operator/config/samples/ray-cluster.mini.yaml)	Small example consisting of 1 head pod.
[ray-cluster.heterogeneous.yaml](https://ray-project.github.io/kuberay/components/operator/config/samples/ray-cluster.heterogeneous.yaml)	Example with heterogenous worker types. 1 head pod and 2 worker pods, each of which has a different resource quota.
[ray-cluster.complete.yaml](https://ray-project.github.io/kuberay/components/operator/config/samples/ray-cluster.complete.yaml)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by Jeffwan** [comment]
@goswamig Thanks for pointing it out! If you can file a PR to help fix it, that would be great!

**Comment by goswamig** [comment]
https://github.com/ray-project/kuberay/pull/305

**Comment by Jeffwan** [comment]
Our component docs are actually soft links to exiting README.md files. 

![image](https://user-images.githubusercontent.com/4739316/177050251-6ebc5f02-9d30-4841-95c9-a445a030de64.png)

The tricky thing is all the referenced files (../config/xxx/xx.yaml) are not included in `docs` (mkdoc site) folder. That's the reason files are missing.
![image](https://user-images.githubusercontent.com/4739316/177050353-da446969-2908-48d1-a3e0-d5fb47484b28.png)

We can see the warning messages when building the docs as well
![image](https://user-images.githubusercontent.com/4739316/177050369-98039651-8112-4508-b274-5761f6ee17c8.png)

I am thinking a better way to solve the issue instead of directly update the path. We want to make sure Github README.md and mkdocs work at the same time.

**Comment by goswamig** [comment]
Makes sense, let me know if I could help anyway. I haven't build the doc but happy to try it out :)
