### ISSUE TITLE
Add support for rolling updates when cluster config changes are applied

### ISSUE THREAD

**Issue by tgaddair** [ray-project/kuberay#40]
For example, the user may wish to patch the cluster spec with a new container image. When this happens, ideally the operator would reconcile the new spec with the runnings pods by spinning up new pods, draining traffic from the old ones, then removing the old pods. This would primarily be useful for long-running clusters (e.g., Ray Serve) that ideally should be upgraded with zero downtime.

cc @Jeffwan

**Comment by Jeffwan** [comment]
Attach some offline discussion here. I think this is a valid use case especially for long running clusters. 

Live upgrade need support of both control plane and data plane.  

1. **Control plane** requires non-stop head service and graceful handling of those inflight requests,
2. **Data plane** needs similar mechanism like Kubernetes drain node in order to migrate actors to other nodes. I think some work might be done on Ray core part to support this.

As @DmitriGekhtman said, A fully general rolling upgrade is going to be hard achieve for a while.

We can do some investigations and collect requirements for Ray core.

**Comment by DmitriGekhtman** [comment]
It's tracked elsewhere.
