### ISSUE TITLE
Add helm chart

### ISSUE THREAD

**Issue by chenk008** [ray-project/kuberay#41]
A helm chart is a collection of files that describe a related set of Kubernetes resources. It can help user to deploy ray-operator and ray cluster conveniently.

**Comment by zhuangzhuang131419** [comment]
I take this issue

**Comment by Jeffwan** [comment]
Do you use helm chart internally? is kustomize enough for deployment?

**Comment by chenk008** [comment]
@Jeffwan We use kustomize to deploy into different Kubernetes clusters, and deliver helm chart to other users who want try ant on their Kubernetes clusters.

**Comment by Jeffwan** [comment]
That makes sense. Normally, one common problem we meet in the past is it's hard to maintain a "source of truth" manifest. kustomize and helm will be organized in different folder. that means whenever we update a manifest, we need to update both source. I don't have big concern here, we can add some contributing guidance to remind contributor to update both. 

BTW, since kustomize is built into kubectl since 1.14.I think that's easy for end user as well. The down side is user can not do customization like Helm.

**Comment by Jeffwan** [comment]
This can be closed. Thanks for @zhuangzhuang131419's effort!
