### ISSUE TITLE
[Feature] [documentation] Autogenerate CR docs

### ISSUE THREAD

**Issue by DmitriGekhtman** [ray-project/kuberay#438]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Docs for KubeRay CRs should be auto-generated and added to an API reference section in the KubeRay documentation.

I wonder if KubeBuilder itself includes some functionality to do this kind of auto-generation?

### Use case

Document functionality fully without having to link to the actual source of truth (go structs).

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by DmitriGekhtman** [comment]
cc @cadedaniel

**Comment by rudeigerc** [comment]
I have tried [elastic/crd-ref-docs](https://github.com/elastic/crd-ref-docs) to generate API documentation of CRD with other Kubernetes Operator projects and it works well. Here is an example of generated docs with KubeRay using `crd-ref-docs`.

However since the main part of KubeRay documentation seems to be hosted on Ray documentation currently, I am not sure where to place the generated references.

/cc @cadedaniel @kevin85421 

---
# API Reference

## Packages
- [ray.io/v1alpha1](#rayiov1alpha1)


## ray.io/v1alpha1


Package v1alpha1 contains API Schema definitions for the ray v1alpha1 API group

### Resource Types
- [RayCluster](#raycluster)
- [RayJob](#rayjob)
- [RayService](#rayservice)



#### AppStatus





_Appears in:_
- [RayServiceStatus](#rayservicestatus)

| Field | Description |
| --- | --- |
| `message` _string_ |  |
| `lastUpdateTime` _[Time](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#time-v1-meta)_ |  |
| `healthLastUpdateTime` _[Time](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#time-v1-meta)_ | Keep track of how long the service is healthy. Update when Serve deployment is healthy or first time convert to unhealthy from healthy. |
| `serveDeploymentStatuses` _object (keys:string, values:[ServeDeploymentStatus](#servedeploymentstatus))_ |  |


#### AutoscalerOptions



AutoscalerOptions specifies optional configuration for the Ray autoscaler.

_Appears in:_
- [RayClusterSpec](#rayclusterspec)

| Field | Description |
| --- | --- |
| `resources` _[ResourceRequirements](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#resourcerequirements-v1-core)_ | Resources specifies optional resource request and limit overrides for the autoscaler container. Default values: 500m CPU request and limit. 512Mi memory request and limit. |
| `image` _string_ | Image optionally overrides the autoscaler's container image. This override is for provided for autoscaler testing and development. |
| `imagePullPolicy` _[PullPolicy](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#pullpolicy-v1-core)_ | ImagePullPolicy optionally overrides the autoscaler container's image pull policy. This override is for provided for autoscaler testing and development. |
| `env` _[EnvVar](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#envvar-v1-core) array_ | Optional list of environment variables to set in the autoscaler container. |
| `envFrom` _[EnvFromSource](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#envfromsource-v1-core) array_ | Optional list of sources to populate environment variables in the autoscaler container. |
| `volumeMounts` _[VolumeMount](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#volumemount-v1-core) array_ | Optional list of volumeMounts.  This is needed for enabling TLS for the autoscaler container. |
| `securityContext` _[SecurityContext](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#securitycontext-v1-core)_ | SecurityContext defines the security options the container should be run with. If set, the fields of SecurityContext override the equivalent fields of PodSecurityContext. More info: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/ |
| `idleTimeoutSeconds` _integer_ | IdleTimeoutSeconds is the number of seconds to wait before scaling down a worker pod which is not using Ray resources. Defaults to 60 (one minute). It is not read by the KubeRay operator but by the Ray autoscaler. |
| `upscalingMode` _[UpscalingMode](#upscalingmode)_ | UpscalingMode is "Conservative", "Default", or "Aggressive." Conservative: Upscaling is rate-limited; the number of pending worker pods is at most the size of the Ray cluster. Default: Upscaling is not rate-limited. Aggressive: An alias for Default; upscaling is not rate-limited. It is not read by the KubeRay operator but by the Ray autoscaler. |
---

**Comment by rudeigerc** [comment]
I have noticed that there is an [API Reference](https://docs.ray.io/en/latest/cluster/kubernetes/references.html) field in the Ray documentation, maybe it's a good choice. But you will have to sync the documentation when releasing KubeRay since it is in the seperated repository. WDYT?

/cc @cadedaniel @kevin85421

**Comment by kevin85421** [comment]
Thanks, @rudeigerc!

> I have noticed that there is an [API Reference](https://docs.ray.io/en/latest/cluster/kubernetes/references.html) field in the Ray documentation, maybe it's a good choice.

I would prefer to add a link in the Ray repository that directs to the API reference in the KubeRay repository. By the way, I plan to upgrade the CRD version shortly. Would it be acceptable to create the API reference after I upgrade the CRD version?

**Comment by rudeigerc** [comment]
Sounds good to me :) Sure. I'm happy to submit a PR after that.
