### ISSUE TITLE
[Feature] need sync for manifests and helm chart 

### ISSUE THREAD

**Issue by scarlet25151** [ray-project/kuberay#446]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

In https://github.com/ray-project/kuberay/blob/76f96bf5a05651611f9a8734c34c2a7f23f54b54/ray-operator/Makefile#L49-L50
we may find there is only crds synced and if there is modification in RBAC, we may forget to sync and may cause some RBAC failure, for example add new rayjobs resource verbs and we forget to update the chart manually.

### Use case

we may use `make helm` to sync all the roles as well as crds.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
Hi @scarlet25151,

Thank you for pointing this out!

Can you explain more about the reason that we need CRD files in the `helm-chart/kuberay-operator/crds` directory? In my understanding, we always use the CRD YAML files in `ray-operator/config/crd/bases` ([Link](https://github.com/ray-project/kuberay/tree/master/ray-operator/config/crd/bases)). That is, we can install CRD by the following commands:

```bash
# Method1: Use online YAML files.
kubectl create -k "github.com/ray-project/kuberay/ray-operator/config/crd?ref=v0.3.0&timeout=90s"

# Method2: Clone this repo and use local CRD YAML files.
kubectl create -k ray-operator/config/crd/
```

We can install CRD with either one of the two methods. Next, we can install helm charts. In addition, I have deleted the `helm-chart/kuberay-operator/crds` directory and tested the charts. It works well.

In my opinion, we need `helm-chart/kuberay-operator/crds` only when we publish a new release. 

cc: @DmitriGekhtman

**Comment by DmitriGekhtman** [comment]
Yeah, this is a little tricky.

The benefit of including CRDs in the Helm chart are

1. It decreases the number of steps required for basic default installation.
2. It makes the UX more consistent -- you can use Helm for everything instead of having to use a combo of Helm and Kustomize.
3. For better or for worse, the CRDs are already in the Helm chart. Deleting them would introduce a backwards incompatibility.

The benefits of including CRDs externally (and having the option to skip them from the chart) are
1. Installing CRDs might be perceived as a sensitive cluster-level operation, to be handled separate by cluster admins.
2. Helm CRD experience might be a little inconsistent due to the problem we have with `kubectl apply` https://github.com/ray-project/kuberay/issues/271
3. Helm is not required, it of course makes sense to keep a primary copy outside of the charts.

Also, I'll mention that the operator Helm chart's RBAC must be kept in sync with the KubeBuilder-generated RBAC outside of the Helm chart. I don't think there's any way to get around that.

My counterargument to syncing crds/RBAC only when we do a release: We should aim to keep the tip of master in a state that is ready to be released with minimal steps required. Release branches and master should look as similar as possible. Developers should be able to deploy from master using more-or-less the same workflows followed by users to deploy stable versions.

**Comment by kevin85421** [comment]
Thanks @DmitriGekhtman! I just realized that Helm can help users install CRDs by `helm install` after the arrival of Helm 3. I will work on this issue.

* https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#method-1-let-helm-do-it-for-you

**Comment by DmitriGekhtman** [comment]
Yep -- I think it's reasonable to state the requirement that Helm 3 must be used.
