### ISSUE TITLE
[Bug] autoscaler not working properly in rayjob

### ISSUE THREAD

**Issue by loleek** [ray-project/kuberay#532]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

When I submit a rayjob into k8s with autoscaler, the autoscaler not work properly. New pod did created but another pod terminated suddenly, and the number of pods equals replica in raycluster spec.
I think there has conflicts between rayjob controller and kuberay autoscaler.
The autoscaler did modified replicas in raycluster workergroup but then rayjob controller do a diff check on raycluster spec between  k8s and rayjob spec and roll it back.
There are some messages can help.
pic1 : autoscaler log
![image](https://user-images.githubusercontent.com/8803670/188603327-d46c0163-3ff7-4d21-b74c-339236a35f8c.png)
pic2 : the object has been modified error in operator
![image](https://user-images.githubusercontent.com/8803670/188602350-09949f1f-a98e-4a96-a6db-826ea20a54a7.png)
pic3 : operator update raycluster spec
![image](https://user-images.githubusercontent.com/8803670/188604106-54b4ce95-02ee-4f7b-9426-73e37e4989c4.png)

### Reproduction script

[hp-pi-autoscale-job.txt](https://github.com/ray-project/kuberay/files/9495509/hp-pi-autoscale-job.txt)
[code-pi-cm.txt](https://github.com/ray-project/kuberay/files/9495510/code-pi-cm.txt)

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

**Comment by DmitriGekhtman** [comment]
Hi, can you share the configuration you used to deploy the RayJob?

**Comment by DmitriGekhtman** [comment]
cc also @harryge00 @Jeffwan

**Comment by loleek** [comment]
> Hi, can you share the configuration you used to deploy the RayJob?
The configuration in the "Reproduction script" part, [hp-pi-autoscale-job.txt](https://github.com/ray-project/kuberay/files/9495509/hp-pi-autoscale-job.txt) is the rayjob-spec.

**Comment by DmitriGekhtman** [comment]
> > Hi, can you share the configuration you used to deploy the RayJob?
> 
> The configuration in the "Reproduction script" part, [hp-pi-autoscale-job.txt](https://github.com/ray-project/kuberay/files/9495509/hp-pi-autoscale-job.txt) is the rayjob-spec.

Perfect, thank you!

**Comment by DmitriGekhtman** [comment]
It's probably a bug. We will fix it eventually when we have time to allocate to this.

**Comment by DmitriGekhtman** [comment]
cc @harryge00. We can work on this together.

**Comment by loleek** [comment]
I need to use autoscaler in my ray-job currently. So I will fix it for my own use this days.
I think there are two ways to solve it.
First, just ignore the ray-cluster spec comparison in ray-job controller when autoscaler enable.
Second, make a new lightweight ray-job definition which loose coupling with ray-cluster. This lightweight ray-job controller will do more focused on job management and just do little management on ray-cluster(just create ray-cluster if not exist).
Which one do you think is better? @DmitriGekhtman 
PS: Currently, the ray-cluster can be reused among many ray-jobs. But if "ShutdownAfterJobFinishes" enabled, the first finished ray-job may release the ray-cluster. This maybe another potential problem.

**Comment by DmitriGekhtman** [comment]
I think we can bring this higher in our priority -- I'll take a look today.

**Comment by DmitriGekhtman** [comment]
>  But if "ShutdownAfterJobFinishes" enabled, the first finished ray-job may release the ray-cluster. This maybe another potential problem.

Could you clarify what you mean by "release"? I think the expected behavior would be to tear down the cluster (for the purposes of cost saving).

**Comment by DmitriGekhtman** [comment]
> I need to use autoscaler in my ray-job currently.

Could you say more about your use-case. How do you intend to leverage autoscaling when running a RayJob?

**Comment by loleek** [comment]
> > But if "ShutdownAfterJobFinishes" enabled, the first finished ray-job may release the ray-cluster. This maybe another potential problem.
> 
> Could you clarify what you mean by "release"? I think the expected behavior would be to tear down the cluster (for the purposes of cost saving).

What I mean is the cluster will tear down, but there has no check if this cluster is used by another rayjob.

**Comment by loleek** [comment]
> > I need to use autoscaler in my ray-job currently.
> 
> Could you say more about your use-case? How do you intend to leverage autoscaling when running a RayJob?

I have one k8s cluster in cloud to run many ray-job with different priority(high, middle, low), higher priority ray-job need more resources even run out of all resources at some time. There will be preemption in k8s, but high priority job not always use all resources, so to improve resource usage, the high priority ray-job should shrink its cluster.

**Comment by loleek** [comment]
> > > But if "ShutdownAfterJobFinishes" enabled, the first finished ray-job may release the ray-cluster. This maybe another potential problem.
> > 
> > 
> > Could you clarify what you mean by "release"? I think the expected behavior would be to tear down the cluster (for the purposes of cost saving).
> 
> What I mean is the cluster will tear down, but there has no check if this cluster is used by another rayjob.

I do some tests, currently the rayclustername is in status scope which can not set in my yaml. So existing raycluster cannot be reused by other rayjobs. There has no the bug what I said. But should we support submit a kube rayjob onto an existing ray cluster?

**Comment by harryge00** [comment]
@loleek You can try set `clusterSelector` as label selectors which select running rayclusters, while leave `rayClusterSpec` empty.

**Comment by loleek** [comment]
> @loleek You can try set `clusterSelector` as label selectors which select running rayclusters, while leave `rayClusterSpec` empty.

ok. I find it in master branch, which 0.3.0 not support.

**Comment by DmitriGekhtman** [comment]
RayJobs are new and under active development -- trying out master is a fruitful thing to do :)

**Comment by kevin85421** [comment]
cc @Yicheng-Lu-llll would you mind taking a look at this issue?

**Comment by Yicheng-Lu-llll** [comment]
sure

**Comment by Yicheng-Lu-llll** [comment]
## Repriduce
I am able to reproduce this issue with the Kind cluster.  reproduction file can be found [here](https://github.com/Yicheng-Lu-llll/kuberay/blob/tmp/ray_v1alpha1_rayjob.yaml), which is similar to the [hp-pi-autoscale-job.txt](https://github.com/ray-project/kuberay/files/9495509/hp-pi-autoscale-job.txt). but used the latest version of Kuberay and Ray 2.4.0.



I believe the root cause of the problem lies in this section of the code:

https://github.com/ray-project/kuberay/blob/3571d52d723de7135338b6d5f9a41fb9b2e972f0/ray-operator/controllers/ray/rayjob_controller.go#L379-L382




##  The sequence of events is as follows:

1. RayJob operator creates a Ray cluster with 1 head pod and 1 worker pod.

2. Based on the workload (placement group in this case), the autoscaler adjusts the RayCluster replica count to 2.
3. The RayCluster operator creates a new worker pod.
4. During the reconciliation of the RayJob operator, it executes the above-mentioned code, overwriting `RayClusterInstance.Spec` with `RayJobInstance.Spec.RayClusterSpec`. As a result, the replica count reverts to its original value of 1.
5. The RayCluster operator deletes an existing worker pod based on the updated replica count.
6. So, we can see "New pod did created but another pod terminated suddenly."


## Screenshot
Here is a screenshot illustrating the issue. The autoscaler does increase the replica count (visible in the log on the right), but it is later overwritten to its original value (visible in the log on the left). I have logged the replica value before and after overwriting.

![demo](https://user-images.githubusercontent.com/51814063/236074581-52b9f76f-43be-43be-b620-14383a7e4493.png)






## Fix


I'm not sure why we need to overwrite `RayClusterInstance.Spec` with `RayJobInstance.Spec.RayClusterSpec`. I would appreciate any insights from @harryge00 on this matter. 

One possible quick fix could be to avoid overwriting the replica value.

**Comment by Yicheng-Lu-llll** [comment]
As previously mentioned, the root cause stems from both the autoscaler (based on the workload) and Ray job controllers (based on the Ray job YAML file) attempting to update the replica count simultaneously. Consider these points:

1. RayCluster currently only permits replica updates; modifying other specs may cause errors.
2. When the autoscaler is enabled, users are less likely to manually adjust the replica count, as the autoscaler should adapt the replica based on workload.

So, a potential solution to address this issue is:

1. Preventing Ray job controllers from updating the RayCluster when the autoscaler is enabled.
2.  Even when the autoscaler is not enabled, Ray job controllers should only modify the replica, rather than the entire RayClusterSpec.
